<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Amits-MacBook-Pro.local" ignored="1" name="test1" tests="7" failures="2" timestamp="2020-09-18T10:54:32 IST" time="0.063" errors="0">
  <testcase name="anotherMethod" time="0.006" classname="com.tpddl.apps.learntestng.AppTest"/>
  <testcase name="collectData" time="0.001" classname="com.tpddl.apps.learntestng.AppTest"/>
  <testcase name="testRegister" time="0.003" classname="com.tpddl.apps.learntestng.AppTest"/>
  <testcase name="testUserLogin" time="0.002" classname="com.tpddl.apps.learntestng.AppTest"/>
  <testcase name="testUserLogin" time="0.002" classname="com.tpddl.apps.learntestng.AppTest">
    <failure type="java.lang.AssertionError" message="expected [222] but found [ram]">
      <![CDATA[java.lang.AssertionError: expected [222] but found [ram]
at com.tpddl.apps.learntestng.AppTest.testUserLogin(AppTest.java:68)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testUserLogin -->
  <testcase name="testUserLogin" time="0.001" classname="com.tpddl.apps.learntestng.AppTest">
    <failure type="java.lang.AssertionError" message="expected [333] but found [shyam]">
      <![CDATA[java.lang.AssertionError: expected [333] but found [shyam]
at com.tpddl.apps.learntestng.AppTest.testUserLogin(AppTest.java:68)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testUserLogin -->
  <testcase name="profile" time="0.001" classname="com.tpddl.apps.learntestng.UserTest"/>
  <testcase name="testLogin" time="0.0" classname="com.tpddl.apps.learntestng.AppTest">
    <ignored/>
  </testcase> <!-- testLogin -->
</testsuite> <!-- test1 -->
